### ISSUE TITLE
wrong org name in examples. replace "dash" to "underscore" in all examples

### ISSUE THREAD

**Issue by kharkevich** [lean-delivery/ansible-role-kibana#4]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
any
```

##### STEPS TO REPRODUCE

Use sample playbook from readme:

```yaml
- name: Install kibana
  hosts: kibana-host
  vars:
    elastic_branch: 6
    kibana_host: localhost
    kibana_config:
      xpack.security.enabled: False
  roles:
     - role: lean-delivery.kibana
```

##### EXPECTED RESULTS

Role installed and works properly
##### ACTUAL RESULTS

wrong role name

```
- downloading role 'kibana', owned by lean-delivery
 [WARNING]: - lean-delivery.kibana was NOT installed successfully: - sorry, lean-delivery.kibana was not found on https://galaxy.ansible.com.
```
